### PR TITLE
Improve CI and documentation

### PR DESCRIPTION
**Pull request by networkfusion**
* Ensure GH workflow targets compatibility with Windows XP (if `VS 16.0` still works).
* Builds GH CI on all branches (allows for forks etc.).
* Move macOS build to GH workflow. 
* Fix deprecation issues with artifacts workflow actions in CI.
* Remove commented out code from Azure pipelines to make it easier to check.
* Fixes a number of links in the readme(s).
* Fixes location of image used in doc.
* Adds contact config.
* Adds templates for issues and pull requests.

Requires new artifacts to be tested before this is released!
They were generated here: https://github.com/buu342/N64-UNFLoader/actions/

### CODE REVIEW

**Comment by networkfusion** [comment]
@buu342 I have finished with this PR.
Sorry for packing it all into one... I am like a rag to a bull sometimes.
Hopefully it helps.

**Comment by buu342** [comment]
GitHub's Actions are really cool, however they make it impossible to download the CI builds without having an account at GitHub. See [this issue](https://github.com/actions/upload-artifact/issues/51) for more information.

I'll be happy to merge this as long as the Azure pipelines script is kept!

**Comment by networkfusion** [comment]
Ok, I have reverted the deletion of Azure Pipelines builds and re-added the badge.
Still not sure if it is the best way, and might be worth checking https://learn.microsoft.com/en-us/azure/devops/pipelines/policies/retention?view=azure-devops&tabs=yaml for how long your retention period is for.

I will look at "Pre-Releases" in another PR if/when I get time.

**Comment by buu342** [comment]
Awesome, merged!

**Pull request merged**
